version: "3.8"

services:
  # --- Database ---
  db:
    image: postgres:15
    container_name: trading_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-app_db}
    ports:
      - "${POSTGRES_PORT:-5431}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - trading_network

  # --- Backend (FastAPI) ---
  backend:
    build:
      context: ./backend
    container_name: trading_backend
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-app_db}
    volumes:
      - ./backend:/app
    networks:
      - trading_network

  # --- Frontend (React + NGINX) ---
  frontend:
    build:
      context: ./front
    container_name: trading_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:80"
    networks:
      - trading_network

networks:
  trading_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
