services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trading
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/trading
    ports:
      - "8000:8000"

  frontend:
    build: ./front
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  db_data:
